//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int ACid { get; set; }
        public Nullable<int> ACNid { get; set; }
        public string ACBalance { get; set; }
        public string ACstatus { get; set; }
    
        public virtual User User { get; set; }
    }
}
