//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeTax
    {
        public int Id { get; set; }
        public Nullable<int> IN_FK_NID { get; set; }
        public Nullable<int> TaxAmount { get; set; }
        public Nullable<int> Paid { get; set; }
        public Nullable<int> Balance { get; set; }
        public string Year { get; set; }
    
        public virtual UsersDetail UsersDetail { get; set; }
    }
}
