//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCircular
    {
        public int JCid { get; set; }
        public string Title { get; set; }
        public Nullable<int> Grade { get; set; }
        public string QualificationLevel { get; set; }
        public string Minresult { get; set; }
        public string Department { get; set; }
        public Nullable<int> Agereq { get; set; }
    }
}
