//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EkShebaEntities : DbContext
    {
        public EkShebaEntities()
            : base("name=EkShebaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<FiscalYIncome> FiscalYIncomes { get; set; }
        public virtual DbSet<IncomeTax> IncomeTaxes { get; set; }
        public virtual DbSet<Passport> Passports { get; set; }
        public virtual DbSet<Passportapplication> Passportapplications { get; set; }
        public virtual DbSet<RechargeHistory> RechargeHistories { get; set; }
        public virtual DbSet<RechargeToken> RechargeTokens { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersDetail> UsersDetails { get; set; }
    }
}
