//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passportapplication
    {
        public int Id { get; set; }
        public Nullable<int> PA_FK_NID { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual UsersDetail UsersDetail { get; set; }
    }
}
