//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersDetail()
        {
            this.Accounts = new HashSet<Account>();
            this.Passports = new HashSet<Passport>();
            this.Passportapplications = new HashSet<Passportapplication>();
            this.RechargeHistories = new HashSet<RechargeHistory>();
            this.IncomeTaxes = new HashSet<IncomeTax>();
        }
    
        public int Nid { get; set; }
        public string Name { get; set; }
        public string Age { get; set; }
        public string Adress { get; set; }
        public string PhoneNo { get; set; }
        public string Religion { get; set; }
        public string FathersName { get; set; }
        public string MotherName { get; set; }
        public string Status { get; set; }
        public Nullable<int> FK_Uid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passport> Passports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passportapplication> Passportapplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RechargeHistory> RechargeHistories { get; set; }
        public virtual User User { get; set; }
        public virtual FiscalYIncome FiscalYIncome { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomeTax> IncomeTaxes { get; set; }
    }
}
